// vue-frontend/src/modules/Feed/Feed.vue
<template>
  <v-card
    flat
    class="feed-container"
    data-testid="feed-container"
  >
    <!-- 投稿フォーム -->
    <PostForm
      :user-avatar="userAvatar"
      @submit="handlePostSubmit"
    />

    <div>
      <template v-if="allPosts.length > 0">
        <!-- 投稿がある場合は投稿一覧を表示 -->
        <PostCard
          v-for="post in allPosts"
          :id="post.id"
          :key="post.id"
          :username="post.username"
          :handle="post.handle"
          :avatar="post.avatar"
          :content="post.content"
          :timestamp="post.timestamp"
          :likes="post.likes"
          :comments="post.comments"
          :retweets="post.retweets"
          :is-liked="post.isLiked"
          @like="() => handleLike(post.id, post.isLiked)"
          @comment="() => {}"
          @retweet="() => {}"
          @share="() => {}"
          @edit="handleEdit"
          @delete="handleDelete"
          @avatar-click="onAvatarClick"
        />
      </template>
      
      <template v-else>
        <!-- 投稿がない場合は空の状態メッセージを表示 -->
        <div class="empty-state">
          <div class="empty-state-text">
            まだ投稿がありません。ポストを始めましょう！
          </div>
        </div>
      </template>
      
      <div
        v-if="allPosts.length > 0"
        class="load-more-container"
      >
        <v-btn
          variant="outlined"
          @click="handleLoadMore"
        >
          さらに読み込む
        </v-btn>
      </div>
    </div>

    <PostEditDialog
      :open="editDialogOpen"
      :initial-content="editingPost?.content || ''"
      :loading="updateLoading"
      @close="() => {
        editDialogOpen = false;
        editingPost = null;
      }"
      @save="handleSaveEdit"
    />

    <PostDeleteDialog
      :open="deleteDialogOpen"
      :loading="false"
      @close="() => {
        deleteDialogOpen = false;
        deletingPostId = null;
      }"
      @delete="() => {
        if (deletingPostId) {
          deletePost(deletingPostId);
          deleteDialogOpen = false;
          deletingPostId = null;
        }
      }"
    />
  </v-card>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import PostForm from '@/modules/PostForm/PostForm.vue'
import PostCard from '@/modules/PostCard/PostCard.vue'
import PostEditDialog from '@/modules/PostEditDialog/PostEditDialog.vue'
import PostDeleteDialog from '@/modules/PostDeleteDialog/PostDeleteDialog.vue'
import { usePost } from './api/usePost'
import { useGetPost } from './api/useGetPost'
import { useLike, useUnlike } from './api/useLike'
import { useUpdatePost, useDeletePost } from './api/usePostActions'
import { useCurrentUser } from '@/composables/useCurrentUser'

interface PostData {
  id: number
  username: string
  handle: string
  avatar: string
  content: string
  timestamp: string
  likes: number
  comments: number
  retweets: number
  isLiked: boolean
}

interface FeedProps {
  userAvatar?: string
  initialPosts?: PostData[]
  onAvatarClick?: () => void
}

const props = withDefaults(defineProps<FeedProps>(), {
  initialPosts: () => []
})

// 認証ユーザー情報を取得
const { user } = useCurrentUser()

const editDialogOpen = ref(false)
const editingPost = ref<{id: number, content: string} | null>(null)
const deleteDialogOpen = ref(false)
const deletingPostId = ref<number | null>(null)
const offset = ref(0)
const limit = ref(20)
const allPosts = ref<PostData[]>(props.initialPosts)

// 投稿一覧を取得するカスタムフック
const {
  data: newPosts,
  refetch: postRefetch,
} = useGetPost(offset.value, limit.value)

watch([newPosts, offset], ([posts, currentOffset]) => {
  if (posts && posts.length > 0) {
    if (currentOffset === 0) {
      allPosts.value = posts
    } else {
      allPosts.value = [...allPosts.value, ...posts]
    }
  }
})

// 投稿を作成するカスタムフック（投稿後にフィードを再取得）
const { mutate: post } = usePost(() => {
  offset.value = 0
  postRefetch()
})

const { mutate: likePost } = useLike(() => postRefetch())
const { mutate: unlikePost } = useUnlike(() => postRefetch())
const { mutate: updatePost, isPending: updateLoading } = useUpdatePost(() => postRefetch())
const { mutate: deletePost } = useDeletePost(() => {
  offset.value = 0
  postRefetch()
})

/**
 * 投稿フォームからの送信時に呼ばれるハンドラ
 */
const handlePostSubmit = async (content: string) => {
  console.log(user.value)
  post({
    content,
  })
}

/**
 * いいねボタンクリック時のハンドラ
 */
const handleLike = (postId: number, isLiked: boolean) => {
  if (isLiked) {
    unlikePost(postId)
  } else {
    likePost(postId)
  }
}

const handleEdit = (postId: number, content: string) => {
  editingPost.value = { id: postId, content }
  editDialogOpen.value = true
}

const handleSaveEdit = (content: string) => {
  if (editingPost.value) {
    updatePost({ postId: editingPost.value.id, content })
    editDialogOpen.value = false
    editingPost.value = null
  }
}

const handleDelete = (postId: number) => {
  deletingPostId.value = postId
  deleteDialogOpen.value = true
}

const handleLoadMore = () => {
  offset.value = offset.value + limit.value
}
</script>

<style scoped>
.feed-container {
  background-color: white;
  border: none;
  box-shadow: none;
}

.empty-state {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 48px 16px;
}

.empty-state-text {
  color: rgb(83, 100, 113);
  font-size: 15px;
  line-height: 20px;
}

.load-more-container {
  display: flex;
  justify-content: center;
  margin-top: 16px;
}
</style>

// sns-frontend/src/modules/Feed/Feed.tsx
/**
 * @fileoverview フィードコンポーネント
 * ホームページのメインコンテンツとして、投稿フォームと投稿一覧を表示します。
 * 投稿の取得・投稿機能をAPI連携して実装しています。
 */
import React, { useState, useEffect } from "react";
import { Box, Typography, Paper, Button } from "@mui/material";
import { PostForm } from "@/modules/PostForm";
import { PostCard } from "@/modules/PostCard";
import { usePost } from "./api/usePost";
import { useAuthenticator } from "@aws-amplify/ui-react";
import { useGetPost } from "./api/useGetPost";
import { useLike, useUnlike } from "./api/useLike";
import { useUpdatePost, useDeletePost } from "./api/usePostActions";
import { PostEditDialog } from "@/modules/PostEditDialog";
import { PostDeleteDialog } from "@/modules/PostDeleteDialog";
import {
  paperStyles,
  emptyStateStyles,
  emptyStateTextStyles,
} from "./styles";

/**
 * フィードコンポーネントのプロパティ定義
 * 
 * @interface FeedProps
 * @property {string} [userAvatar] - 投稿フォームに表示するユーザーアバター画像URL
 * @property {Array<PostData>} [initialPosts=[]] - 初期表示する投稿データ配列
 * @property {(page: string, username?: string) => void} [onAvatarClick] - アバタークリック時のコールバック
 */
export interface FeedProps {
  userAvatar?: string;
  initialPosts?: Array<{
    id: number;
    username: string;
    handle: string;
    avatar: string;
    content: string;
    timestamp: string;
    likes: number;
    comments: number;
    retweets: number;
    isLiked: boolean;
  }>;
  onAvatarClick?: (page: string, username?: string) => void;
}

/**
 * フィードコンポーネント
 * 投稿フォームと投稿一覧を表示し、投稿の作成や表示を管理します
 * 
 * @param {FeedProps} props - フィードコンポーネントのプロパティ
 * @returns {React.ReactElement} フィードコンポーネント
 */
export const Feed: React.FC<FeedProps> = ({ userAvatar, initialPosts = [], onAvatarClick }) => {
  // 認証ユーザー情報を取得
  const { user } = useAuthenticator((context) => [context.user]);

  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [editingPost, setEditingPost] = useState<{id: number, content: string} | null>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deletingPostId, setDeletingPostId] = useState<number | null>(null);
  const [offset, setOffset] = useState(0);
  const [limit] = useState(20);
  const [allPosts, setAllPosts] = useState<any[]>(initialPosts);

  // 投稿一覧を取得するカスタムフック
  const {
    data: newPosts = [],
    refetch: postRefetch,
  } = useGetPost(offset, limit);

  useEffect(() => {
    if (newPosts && newPosts.length > 0) {
      if (offset === 0) {
        setAllPosts(newPosts);
      } else {
        setAllPosts(prev => [...prev, ...newPosts]);
      }
    }
  }, [newPosts, offset]);

  // 投稿を作成するカスタムフック（投稿後にフィードを再取得）
  const { mutate: post } = usePost(() => {
    setOffset(0);
    postRefetch();
  });

  const { mutate: likePost } = useLike(() => postRefetch());
  const { mutate: unlikePost } = useUnlike(() => postRefetch());
  const { mutate: updatePost, isPending: updateLoading } = useUpdatePost(() => postRefetch());
  const { mutate: deletePost } = useDeletePost(() => {
    setOffset(0);
    postRefetch();
  });

  /**
   * 投稿フォームからの送信時に呼ばれるハンドラ
   * 
   * @param {string} content - 投稿内容
   */
  const handlePostSubmit = async (content: string) => {
    console.log(user);
    post({
      content,
    });
  };

  /**
   * いいねボタンクリック時のハンドラ
   */
  const handleLike = (postId: number, isLiked: boolean) => {
    if (isLiked) {
      unlikePost(postId);
    } else {
      likePost(postId);
    }
  };

  const handleEdit = (postId: number, content: string) => {
    setEditingPost({ id: postId, content });
    setEditDialogOpen(true);
  };

  const handleSaveEdit = (content: string) => {
    if (editingPost) {
      updatePost({ postId: editingPost.id, content });
      setEditDialogOpen(false);
      setEditingPost(null);
    }
  };

  const handleDelete = (postId: number) => {
    setDeletingPostId(postId);
    setDeleteDialogOpen(true);
  };

  const handleLoadMore = () => {
    setOffset(prev => prev + limit);
  };

  return (
    <Paper elevation={0} sx={paperStyles} data-testid="feed-container">
      {/* 投稿フォーム */}
      <PostForm userAvatar={userAvatar} onSubmit={handlePostSubmit} />

      <Box>
        {allPosts.length > 0 ? (
          // 投稿がある場合は投稿一覧を表示
          allPosts.map((post) => (
            <PostCard
              key={post.id}
              id={post.id}
              username={post.username}
              handle={post.handle}
              avatar={post.avatar}
              content={post.content}
              timestamp={post.timestamp}
              likes={post.likes}
              comments={post.comments}
              retweets={post.retweets}
              isLiked={post.isLiked}
              onLike={() => handleLike(post.id, post.isLiked)}
              onComment={() => {}}
              onRetweet={() => {}}
              onShare={() => {}}
              onEdit={handleEdit}
              onDelete={handleDelete}
              onAvatarClick={onAvatarClick}
            />
          ))
        ) : (
          // 投稿がない場合は空の状態メッセージを表示
          <Box sx={emptyStateStyles}>
            <Typography variant="body1" sx={emptyStateTextStyles}>
              まだ投稿がありません。ポストを始めましょう！
            </Typography>
          </Box>
        )}
        {allPosts.length > 0 && (
          <Box sx={{ display: 'flex', justifyContent: 'center', mt: 2 }}>
            <Button onClick={handleLoadMore} variant="outlined">
              さらに読み込む
            </Button>
          </Box>
        )}
      </Box>

      <PostEditDialog
        open={editDialogOpen}
        onClose={() => {
          setEditDialogOpen(false);
          setEditingPost(null);
        }}
        onSave={handleSaveEdit}
        initialContent={editingPost?.content || ''}
        loading={updateLoading}
      />

      <PostDeleteDialog
        open={deleteDialogOpen}
        onClose={() => {
          setDeleteDialogOpen(false);
          setDeletingPostId(null);
        }}
        onDelete={() => {
          if (deletingPostId) {
            deletePost(deletingPostId);
            setDeleteDialogOpen(false);
            setDeletingPostId(null);
          }
        }}
        loading={false}
      />
    </Paper>
  );
};
