// sns-frontend/src/modules/PostDeleteDialog/PostDeleteDialog.tsx
import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
} from '@mui/material';

interface PostDeleteDialogProps {
  open: boolean;
  onClose: () => void;
  onDelete: () => void;
  loading?: boolean;
}

export const PostDeleteDialog: React.FC<PostDeleteDialogProps> = ({
  open,
  onClose,
  onDelete,
  loading = false,
}) => {
  const handleDelete = () => {
    onDelete();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>投稿を削除</DialogTitle>
      <DialogContent>
        <Typography variant="body1">
          この投稿を削除しますか？この操作は取り消すことができません。
        </Typography>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={loading}>
          キャンセル
        </Button>
        <Button
          onClick={handleDelete}
          variant="contained"
          color="error"
          disabled={loading}
        >
          {loading ? '削除中...' : '削除'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

// vue-frontend/src/modules/PostDeleteDialog/PostDeleteDialog.vue
<template>
  <v-dialog
    :model-value="open"
    max-width="600px"
    persistent
    @update:model-value="onClose"
  >
    <v-card>
      <v-card-title>投稿を削除</v-card-title>
      
      <v-card-text>
        <p class="text-body-1">
          この投稿を削除しますか？この操作は取り消すことができません。
        </p>
      </v-card-text>
      
      <v-card-actions>
        <v-spacer />
        <v-btn
          :disabled="loading"
          variant="text"
          @click="onClose"
        >
          キャンセル
        </v-btn>
        <v-btn
          :disabled="loading"
          variant="flat"
          color="error"
          @click="handleDelete"
        >
          {{ loading ? '削除中...' : '削除' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
interface PostDeleteDialogProps {
  open: boolean
  onClose: () => void
  onDelete: () => void
  loading?: boolean
}

const props = withDefaults(defineProps<PostDeleteDialogProps>(), {
  loading: false
})

const handleDelete = () => {
  props.onDelete()
}
</script>
